### ISSUE TITLE
Dodatne loptice

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG73-elimination#1]
Dodati loptice razlicitih osobina. Na primer neka ako se uhvati smanjuje poene ili usporava igraca na kratko.

**Comment by jovana144** [comment]
Dodala sam loptice razlicitih boja, koje imaju razlicit broj poena i na osnovu tih poena uvecavaju ili umanjuju skor. Dodatno objasnjenje za ovaj dodatak, kao i za izgled animacije ostavila sam u README.md i na wiki strani.
