### ISSUE TITLE
Dodatna animacija

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG73-elimination#2]
Primeri sta se moze dodati:
- Dodati animaciju hvatanja loptice
- Dodati animaciju zavrsetka igre, gde igrac seda na pod i tuguje pre nego sto iskoci GAME OVER ekran

**Comment by jovana144** [comment]
Dodala sam animaciju, gde igrac sedi i tuguje nakon sto je izgubio.

**Comment by rastko-djordjevic-edu** [comment]
Animacija je super odradjena, osetio sam njegovu tugu.
